[debug] [2017-12-03T21:00:54.380Z] ----------------------------------------------------------------------
[debug] [2017-12-03T21:00:54.382Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy
[debug] [2017-12-03T21:00:54.383Z] CLI Version:   3.15.2
[debug] [2017-12-03T21:00:54.383Z] Platform:      darwin
[debug] [2017-12-03T21:00:54.383Z] Node Version:  v6.11.2
[debug] [2017-12-03T21:00:54.384Z] Time:          Sun Dec 03 2017 13:00:54 GMT-0800 (PST)
[debug] [2017-12-03T21:00:54.384Z] ----------------------------------------------------------------------
[debug] 
[debug] [2017-12-03T21:00:54.404Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2017-12-03T21:00:54.405Z] > authorizing via signed-in user
[debug] [2017-12-03T21:00:54.407Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2017-12-03T21:00:54.407Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token { refresh_token: '1/G9KpFiiEbkIYaXh8RxL8NAnPXOFC33bUmYvBE0QjDpRrD27sFo_NdyiXoZLYEc8q',
  client_id: '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
  client_secret: 'j9iVZfS8kkCEFUPaAeJV0sAi',
  grant_type: 'refresh_token',
  scope: 'email https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/cloudplatformprojects.readonly https://www.googleapis.com/auth/firebase openid' } 
 Sun Dec 03 2017 13:00:54 GMT-0800 (PST)
[debug] [2017-12-03T21:00:54.675Z] <<< HTTP RESPONSE 200
[debug] [2017-12-03T21:00:54.683Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/cse-134b-hw2-702d4  
 Sun Dec 03 2017 13:00:54 GMT-0800 (PST)
[debug] [2017-12-03T21:00:55.281Z] <<< HTTP RESPONSE 200
[debug] [2017-12-03T21:00:55.282Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/cse-134b-hw2-702d4/tokens  
 Sun Dec 03 2017 13:00:55 GMT-0800 (PST)
[debug] [2017-12-03T21:00:55.944Z] <<< HTTP RESPONSE 200
[info] 
[info] === Deploying to 'cse-134b-hw2-702d4'...
[info] 
[info] i  deploying hosting
[info] i  hosting: preparing public directory for upload...
[debug] [2017-12-03T21:00:57.314Z] >>> HTTP REQUEST PUT https://deploy.firebase.com/v1/hosting/cse-134b-hw2-702d4/uploads/-L-TAd0_piZyJEsFQg_S?fileCount=214&message=  
 Sun Dec 03 2017 13:00:57 GMT-0800 (PST)
[debug] [2017-12-03T21:01:07.109Z] <<< HTTP RESPONSE 502
[debug] [2017-12-03T21:01:07.109Z] <<< HTTP RESPONSE BODY <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

[debug] [2017-12-03T21:01:07.111Z] TypeError: Cannot create property 'error' on string '<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
'
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:11:16)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:43:25)
    at Request.self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
[error] 
[error] Error: An unexpected error has occurred.
